dbt_users_app:
  outputs:
    dev:
      dbname: userdb
      host: localhost
      pass: Jamesbond1
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev
users_project:
  outputs:
    dev:
      dbname: userdb
      host: localhost
      pass: Jamesbond1
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev
