# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



env:
  DBT_PROFILES_DIR: .

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: dbt-version
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt --version"
          dbt_project_folder: "dbt_project"
      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt deps"
          dbt_project_folder: "dbt_project"
      - name: dbt-run
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt run"
          dbt_project_folder: "dbt_project"
      - name: dbt-test
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: "dbt test"
          dbt_project_folder: "dbt_project"

    
